# maxDensity


# this works 
# arq -v --data bulk.ttl --query bulk.rq	

PREFIX : <http://www.example.org/ns/lu/zoning#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?zoning ?density

WHERE {
	?zoning :maxDensity ?density .
}
