name: NLP-SPARQL
channels:
  - conda-forge
  # - pytorch # uncomment for any intel system
  - huggingface
  - intel
  - defaults
dependencies:
  - python = 3.9
  - matplotlib
  - pandas
  - numpy
  - pytest
  - scikit-learn
  - sklearn-pandas
  - ipykernel
  - pathlib
  - xgboost
  - shap
  - pip
  - rdflib
  # - pytorch # uncomment for any intel system
  - keras
  - nltk
  - spacy
  - seaborn
  - gensim
  - transformers
  - datasets
  - apache-beam
  - optuna
  - loguru
  - pip:
    - stanza # as pip package to override pytorch version when installing farm-haystack on M1 macs
    # - farm-haystack # uncomment for any linux intel system with basic features set
    # - farm-haystack[all] # if you want to use CPU on any linux intel system with full features set
    # - farm-haystack[all-gpu] # if you want to use GPU on any linux intel system with full features set
    # for m1 macs need rust, cmake, postgresql install with brew, 
    # and follow instructions at https://docs.haystack.deepset.ai/docs/installation#basic-installation (windows users also follow installation instructions)