name: NLP-SPARQL
channels:
  - conda-forge
  - pytorch
  - huggingface
  - intel
  - defaults
dependencies:
  - python = 3.9
  - matplotlib
  - numpy
  - pandas
  - pytest
  - scikit-learn
  - sklearn-pandas
  - ipykernel
  - pathlib
  - xgboost
  - shap
  - pip
  - rdflib
  - pytorch
  - torchtext
  - keras
  - nltk
  - spacy
  - seaborn
  - gensim
  - transformers
  - datasets
  - apache-beam
  - optuna
  - pip:
    - knockknock
    - farm-haystack[all] # if you want to use CPU
    # - farm-haystack[all-gpu] # if you want to use GPU